application: x-arcanum-801
version: 3
runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /client/
  static_dir: client/
  expiration: "364d 5h"
  application_readable: true

- url: /favicon\.ico
  static_files: client/dist/favicon.ico
  upload: client/dist/favicon.ico
  expiration: "364d 5h"

- url: /robots\.txt
  static_files: client/dist/robots.txt
  upload: client/dist/robots.txt
  expiration: "364d 5h"

- url: /.*
  script: http.app


libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
  
- name: webob
  version: latest


builtins:
- appstats: on
