application: universal-trail-608
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /client/
  static_dir: client/
#  expiration: "364d 5h" # its not ready for cache yet

- url: /favicon\.ico
  static_files: client/static/favicon.ico
  upload: client/static/favicon.ico
  expiration: "364d 5h"

- url: /robots\.txt
  static_files: client/static/robots.txt
  upload: client/static/robots.txt
  expiration: "364d 5h"

- url: /.*
  script: http.app


libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
  
- name: webob
  version: latest


builtins:
- appstats: on
