application: themiraclestyle-testing-site
module: backend
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: B2 # B1 - 128MB; 600Mhz; $0.05 / B2 - 256MB; 1.2Ghz; $0.10 / B4 - 512MB; 2.4Ghz; $0.20 / B4_1G - 1024MB; 2.4Ghz; $0.30 / B8 - 1024MB; 4.8Ghz; $0.40
basic_scaling:
  max_instances: 3
  idle_timeout: 30s

# https://cloud.google.com/appengine/docs/python/modules/#Python_Instance_scaling_and_class
# https://cloud.google.com/appengine/docs/python/config/appconfig#scaling_and_instance_types
# Billing begins when an instance starts and ends fifteen minutes after a basic instance has finished processing its last request.

libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
  
- name: webob
  version: latest

- name: ssl
  version: latest

- name: pycrypto
  version: latest

handlers:
- url: /.*
  script: http.app