application: themiraclestyle-testing-site
module: backend
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: B2
basic_scaling:
  max_instances: 3
  idle_timeout: 5m

libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
  
- name: webob
  version: latest

- name: ssl
  version: latest

handlers:
- url: /.*
  script: http.app