# -*- coding: utf-8 -*-
'''
Created on Jan 16, 2015

@authors:  Edis Sehalic (edis.sehalic@gmail.com), Elvin Kosova (elvinkosova@gmail.com)
'''
ACCOUNT_SUDO_SUBJECT = ''
ACCOUNT_SUDO_BODY = ''

CATALOG_PUBLISH_SUBJECT = ''
CATALOG_PUBLISH_BODY = ''

CATALOG_SUDO_SUBJECT = ''
CATALOG_SUDO_BODY = ''

CATALOG_CATALOG_PROCESS_DUPLICATE_SUBJECT = ''
CATALOG_CATALOG_PROCESS_DUPLICATE_BODY = ''

CATALOG_PRICETAG_PROCESS_DUPLICATE_SUBJECT = ''
CATALOG_PRICETAG_PROCESS_DUPLICATE_BODY = ''

CATALOG_DISCONTINUE_SUBJECT = ''
CATALOG_DISCONTINUE_BODY = ''

ORDER_COMPLETE_SUBJECT = ''
ORDER_COMPLETE_BODY = ''

ORDER_REVIEW_FEEDBACK_SUBJECT = ''
ORDER_REVIEW_FEEDBACK_BODY = ''

ORDER_REPORT_FEEDBACK_SUBJECT = ''
ORDER_REPORT_FEEDBACK_BODY = ''

ORDER_SUDO_FEEDBACK_SUBJECT = ''
ORDER_SUDO_FEEDBACK_BODY = ''

ORDER_LOG_MESSAGE_SUBJECT = ''
ORDER_LOG_MESSAGE_BODY = ''